//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Resources/Input/Vehicle Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VehicleInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VehicleInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Vehicle Input Actions"",
    ""maps"": [
        {
            ""name"": ""Drive"",
            ""id"": ""2b71f418-1e74-43dc-b4f3-d7f713a8b34f"",
            ""actions"": [
                {
                    ""name"": ""Gas Pedal"",
                    ""type"": ""Button"",
                    ""id"": ""ac18c5f0-a031-4f4c-b9d7-946bdc78a9c3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brake Pedal"",
                    ""type"": ""Button"",
                    ""id"": ""42338992-d098-4733-8769-fbd7c0d8c19c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Clutch Pedal"",
                    ""type"": ""Button"",
                    ""id"": ""c11df8d3-61f9-4bce-b015-3d00c7e06e44"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Steering Wheel"",
                    ""type"": ""Button"",
                    ""id"": ""5345d260-5037-4b92-8f09-1bd084ce4255"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""17f3c19d-9633-436c-b9ff-8ee95f236b96"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gas Pedal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f405d88c-2693-4a01-a5e4-0013f12644ec"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake Pedal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""490ccd23-7d8c-4d67-919d-af2851532fc6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clutch Pedal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecf89d8e-3ac3-4943-8c5e-796b77b11ccc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Shifter"",
            ""id"": ""ee1b5437-9055-4ac2-a872-4b6463c8de2b"",
            ""actions"": [
                {
                    ""name"": ""Reverse"",
                    ""type"": ""Button"",
                    ""id"": ""587a2695-b301-4da8-a786-5f7faa227fba"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear 1"",
                    ""type"": ""Button"",
                    ""id"": ""f51eb585-5c0f-4987-9b35-26de4389c0bb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear 2"",
                    ""type"": ""Button"",
                    ""id"": ""609a180a-9d48-44d3-af55-961e28248ea1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear 3"",
                    ""type"": ""Button"",
                    ""id"": ""77c39b36-bfdc-4534-aef3-5c4fb33f3b79"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear 4"",
                    ""type"": ""Button"",
                    ""id"": ""631865cc-1668-4fe5-b6f0-a4dd3eb29b09"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear 5"",
                    ""type"": ""Button"",
                    ""id"": ""abf1d6e3-a43a-4fa1-ad40-06a4b4d7c1a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear 6"",
                    ""type"": ""Button"",
                    ""id"": ""584a0fe9-eae9-4c9b-b9db-27547cbcaba7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Automatic Drive"",
                    ""type"": ""Button"",
                    ""id"": ""6884ce89-785e-42db-98ce-3ed21786b8be"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Automatic Parking"",
                    ""type"": ""Button"",
                    ""id"": ""f5e3ecc5-5a39-4e3f-bfad-be19574cb26c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Automatic Reverse"",
                    ""type"": ""Button"",
                    ""id"": ""f911a994-dcbd-4a08-80b1-e0a6cdb04513"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Automatic Sport"",
                    ""type"": ""Button"",
                    ""id"": ""d8b21512-0fbf-4b6a-826f-c05712821e21"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Automatic Manual"",
                    ""type"": ""Button"",
                    ""id"": ""1c64fdf1-1ac0-43b9-9a69-b82c9e014781"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear Up"",
                    ""type"": ""Button"",
                    ""id"": ""8f27072d-e61d-41be-a423-732aa2ad98a2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear Down"",
                    ""type"": ""Button"",
                    ""id"": ""279a42e0-5c8a-46ed-ba5d-04ac8c8516b5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d56f99c8-21fc-48b3-a58b-49278d8c9ccf"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e8d5d9d-a761-437b-a4ea-43f2da32a8b8"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f29e2d9e-2ed3-4919-a13b-04fd57426651"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92bfa6bf-e39d-4351-9433-833e7756a3c4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5593c489-71df-4a28-a6c7-c9b718c9562d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a3bfeb5-843a-4b72-b288-a3134952e869"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c104f686-9eb7-4818-b93e-7351fed4254d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""447965a1-98f3-479d-b56e-ef833d70e976"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Automatic Drive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35c74075-e7bb-4924-a69e-a4594c045fd2"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Automatic Parking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83b5f3cd-3859-4d0a-bec4-c2ec78e2efaf"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Automatic Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9b5b440-bd46-4945-8043-dfbb062b2e7b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Automatic Sport"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71c5fea9-6e89-4805-99b5-ec48a31661e2"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Automatic Manual"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5989a34c-d1d0-4c42-8485-7b0431e2fc2d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07629d69-f2de-4e88-8ee8-25c161478827"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Functions"",
            ""id"": ""2ab25228-20e1-425c-89af-bfeae88d4412"",
            ""actions"": [
                {
                    ""name"": ""Ignition"",
                    ""type"": ""Button"",
                    ""id"": ""034b5186-d2d3-4b2a-bc47-3d957e0e68d6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Starter"",
                    ""type"": ""Button"",
                    ""id"": ""5e47c18e-ced8-4a6d-bf90-638ea305d042"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Parking Brake"",
                    ""type"": ""Button"",
                    ""id"": ""113eb861-b523-4e30-b6c1-d8e0f8362437"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left Blinker"",
                    ""type"": ""Button"",
                    ""id"": ""350e29a9-35c3-4125-856c-2098d4f8dc09"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right Blinker"",
                    ""type"": ""Button"",
                    ""id"": ""8f8a955a-4119-4af9-b02b-bb7777dee29a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left Comfort Blinker"",
                    ""type"": ""Button"",
                    ""id"": ""9173859a-5d7d-4004-b29c-b7a63aaf6525"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right Comfort Blinker"",
                    ""type"": ""Button"",
                    ""id"": ""b57c1a88-2702-481c-b1c4-9f32384c26b7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hazards"",
                    ""type"": ""Button"",
                    ""id"": ""ca060e54-a956-4409-92a0-27777afe3637"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5ec33688-8c6e-41f6-a18a-2618dabbb589"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""Ignition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""904a11a4-2251-4a02-9b70-f912388f67d6"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""Starter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff686887-add7-4412-a232-af89951b482d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""Parking Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e519e9d-6e43-40b8-b0f8-c5c753ac3d09"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": ""Hold(duration=0.15)"",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""Left Blinker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f3498d8-3f9f-44f9-a8b3-cc4a7f4b5cd6"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": ""Hold(duration=0.15)"",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""Right Blinker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23f2e47d-474d-43f6-868a-0a1d0d89588a"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": ""Tap(duration=0.15)"",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""Left Comfort Blinker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0449cc06-6c5d-4878-9cc4-c529144cc98f"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": ""Tap(duration=0.15)"",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""Right Comfort Blinker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29a64cfb-aeda-40bc-8702-300d15c18337"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hazards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2144a905-10bf-49df-8f1d-e1513ec5344e"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard and Mouse"",
                    ""action"": ""Hazards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""View"",
            ""id"": ""ca04f903-92ab-48fb-a78c-e08b8df8451e"",
            ""actions"": [
                {
                    ""name"": ""Change Vehicle View"",
                    ""type"": ""Button"",
                    ""id"": ""95c5ba36-0618-47eb-ae0e-bd0827e26ea6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Driver View"",
                    ""type"": ""Button"",
                    ""id"": ""9b9b8cc3-30cd-4950-ba34-e26bba39aca1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""View 1"",
                    ""type"": ""Button"",
                    ""id"": ""ecc95be6-dbfe-4bc0-a3e6-841e8bbf765f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dashboard View"",
                    ""type"": ""Button"",
                    ""id"": ""b25c8dc0-92e6-487f-bd7d-ac383bb83884"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Infotainment View"",
                    ""type"": ""Button"",
                    ""id"": ""3f90632b-49fe-4478-9ccd-91bd3c8c81a2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4d3133f9-61a4-49f1-95d7-7403f3a66391"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Vehicle View"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caaba3a8-675d-43d3-a32e-97cf8fac02cd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Driver View"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f7f3aa5-e498-4d2b-a3b9-2ffdf3a36a1a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""View 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1828453-115e-441d-9a2c-ac4e137c200a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dashboard View"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""397fdeb1-9fe2-4c29-8ca5-0ebcaa27095c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Infotainment View"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Trip Computer"",
            ""id"": ""421e9f54-820a-4660-be50-91565684e995"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""ec422daf-aad0-4685-a007-24932a844f39"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c8ad6e3c-7f3d-4de9-9fca-ab059824bbb0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard and Mouse"",
            ""bindingGroup"": ""Keyboard and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Drive
        m_Drive = asset.FindActionMap("Drive", throwIfNotFound: true);
        m_Drive_GasPedal = m_Drive.FindAction("Gas Pedal", throwIfNotFound: true);
        m_Drive_BrakePedal = m_Drive.FindAction("Brake Pedal", throwIfNotFound: true);
        m_Drive_ClutchPedal = m_Drive.FindAction("Clutch Pedal", throwIfNotFound: true);
        m_Drive_SteeringWheel = m_Drive.FindAction("Steering Wheel", throwIfNotFound: true);
        // Shifter
        m_Shifter = asset.FindActionMap("Shifter", throwIfNotFound: true);
        m_Shifter_Reverse = m_Shifter.FindAction("Reverse", throwIfNotFound: true);
        m_Shifter_Gear1 = m_Shifter.FindAction("Gear 1", throwIfNotFound: true);
        m_Shifter_Gear2 = m_Shifter.FindAction("Gear 2", throwIfNotFound: true);
        m_Shifter_Gear3 = m_Shifter.FindAction("Gear 3", throwIfNotFound: true);
        m_Shifter_Gear4 = m_Shifter.FindAction("Gear 4", throwIfNotFound: true);
        m_Shifter_Gear5 = m_Shifter.FindAction("Gear 5", throwIfNotFound: true);
        m_Shifter_Gear6 = m_Shifter.FindAction("Gear 6", throwIfNotFound: true);
        m_Shifter_AutomaticDrive = m_Shifter.FindAction("Automatic Drive", throwIfNotFound: true);
        m_Shifter_AutomaticParking = m_Shifter.FindAction("Automatic Parking", throwIfNotFound: true);
        m_Shifter_AutomaticReverse = m_Shifter.FindAction("Automatic Reverse", throwIfNotFound: true);
        m_Shifter_AutomaticSport = m_Shifter.FindAction("Automatic Sport", throwIfNotFound: true);
        m_Shifter_AutomaticManual = m_Shifter.FindAction("Automatic Manual", throwIfNotFound: true);
        m_Shifter_GearUp = m_Shifter.FindAction("Gear Up", throwIfNotFound: true);
        m_Shifter_GearDown = m_Shifter.FindAction("Gear Down", throwIfNotFound: true);
        // Functions
        m_Functions = asset.FindActionMap("Functions", throwIfNotFound: true);
        m_Functions_Ignition = m_Functions.FindAction("Ignition", throwIfNotFound: true);
        m_Functions_Starter = m_Functions.FindAction("Starter", throwIfNotFound: true);
        m_Functions_ParkingBrake = m_Functions.FindAction("Parking Brake", throwIfNotFound: true);
        m_Functions_LeftBlinker = m_Functions.FindAction("Left Blinker", throwIfNotFound: true);
        m_Functions_RightBlinker = m_Functions.FindAction("Right Blinker", throwIfNotFound: true);
        m_Functions_LeftComfortBlinker = m_Functions.FindAction("Left Comfort Blinker", throwIfNotFound: true);
        m_Functions_RightComfortBlinker = m_Functions.FindAction("Right Comfort Blinker", throwIfNotFound: true);
        m_Functions_Hazards = m_Functions.FindAction("Hazards", throwIfNotFound: true);
        // View
        m_View = asset.FindActionMap("View", throwIfNotFound: true);
        m_View_ChangeVehicleView = m_View.FindAction("Change Vehicle View", throwIfNotFound: true);
        m_View_DriverView = m_View.FindAction("Driver View", throwIfNotFound: true);
        m_View_View1 = m_View.FindAction("View 1", throwIfNotFound: true);
        m_View_DashboardView = m_View.FindAction("Dashboard View", throwIfNotFound: true);
        m_View_InfotainmentView = m_View.FindAction("Infotainment View", throwIfNotFound: true);
        // Trip Computer
        m_TripComputer = asset.FindActionMap("Trip Computer", throwIfNotFound: true);
        m_TripComputer_Newaction = m_TripComputer.FindAction("New action", throwIfNotFound: true);
    }

    ~@VehicleInputActions()
    {
        UnityEngine.Debug.Assert(!m_Drive.enabled, "This will cause a leak and performance issues, VehicleInputActions.Drive.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Shifter.enabled, "This will cause a leak and performance issues, VehicleInputActions.Shifter.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Functions.enabled, "This will cause a leak and performance issues, VehicleInputActions.Functions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_View.enabled, "This will cause a leak and performance issues, VehicleInputActions.View.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_TripComputer.enabled, "This will cause a leak and performance issues, VehicleInputActions.TripComputer.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Drive
    private readonly InputActionMap m_Drive;
    private List<IDriveActions> m_DriveActionsCallbackInterfaces = new List<IDriveActions>();
    private readonly InputAction m_Drive_GasPedal;
    private readonly InputAction m_Drive_BrakePedal;
    private readonly InputAction m_Drive_ClutchPedal;
    private readonly InputAction m_Drive_SteeringWheel;
    public struct DriveActions
    {
        private @VehicleInputActions m_Wrapper;
        public DriveActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @GasPedal => m_Wrapper.m_Drive_GasPedal;
        public InputAction @BrakePedal => m_Wrapper.m_Drive_BrakePedal;
        public InputAction @ClutchPedal => m_Wrapper.m_Drive_ClutchPedal;
        public InputAction @SteeringWheel => m_Wrapper.m_Drive_SteeringWheel;
        public InputActionMap Get() { return m_Wrapper.m_Drive; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DriveActions set) { return set.Get(); }
        public void AddCallbacks(IDriveActions instance)
        {
            if (instance == null || m_Wrapper.m_DriveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DriveActionsCallbackInterfaces.Add(instance);
            @GasPedal.started += instance.OnGasPedal;
            @GasPedal.performed += instance.OnGasPedal;
            @GasPedal.canceled += instance.OnGasPedal;
            @BrakePedal.started += instance.OnBrakePedal;
            @BrakePedal.performed += instance.OnBrakePedal;
            @BrakePedal.canceled += instance.OnBrakePedal;
            @ClutchPedal.started += instance.OnClutchPedal;
            @ClutchPedal.performed += instance.OnClutchPedal;
            @ClutchPedal.canceled += instance.OnClutchPedal;
            @SteeringWheel.started += instance.OnSteeringWheel;
            @SteeringWheel.performed += instance.OnSteeringWheel;
            @SteeringWheel.canceled += instance.OnSteeringWheel;
        }

        private void UnregisterCallbacks(IDriveActions instance)
        {
            @GasPedal.started -= instance.OnGasPedal;
            @GasPedal.performed -= instance.OnGasPedal;
            @GasPedal.canceled -= instance.OnGasPedal;
            @BrakePedal.started -= instance.OnBrakePedal;
            @BrakePedal.performed -= instance.OnBrakePedal;
            @BrakePedal.canceled -= instance.OnBrakePedal;
            @ClutchPedal.started -= instance.OnClutchPedal;
            @ClutchPedal.performed -= instance.OnClutchPedal;
            @ClutchPedal.canceled -= instance.OnClutchPedal;
            @SteeringWheel.started -= instance.OnSteeringWheel;
            @SteeringWheel.performed -= instance.OnSteeringWheel;
            @SteeringWheel.canceled -= instance.OnSteeringWheel;
        }

        public void RemoveCallbacks(IDriveActions instance)
        {
            if (m_Wrapper.m_DriveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDriveActions instance)
        {
            foreach (var item in m_Wrapper.m_DriveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DriveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DriveActions @Drive => new DriveActions(this);

    // Shifter
    private readonly InputActionMap m_Shifter;
    private List<IShifterActions> m_ShifterActionsCallbackInterfaces = new List<IShifterActions>();
    private readonly InputAction m_Shifter_Reverse;
    private readonly InputAction m_Shifter_Gear1;
    private readonly InputAction m_Shifter_Gear2;
    private readonly InputAction m_Shifter_Gear3;
    private readonly InputAction m_Shifter_Gear4;
    private readonly InputAction m_Shifter_Gear5;
    private readonly InputAction m_Shifter_Gear6;
    private readonly InputAction m_Shifter_AutomaticDrive;
    private readonly InputAction m_Shifter_AutomaticParking;
    private readonly InputAction m_Shifter_AutomaticReverse;
    private readonly InputAction m_Shifter_AutomaticSport;
    private readonly InputAction m_Shifter_AutomaticManual;
    private readonly InputAction m_Shifter_GearUp;
    private readonly InputAction m_Shifter_GearDown;
    public struct ShifterActions
    {
        private @VehicleInputActions m_Wrapper;
        public ShifterActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Reverse => m_Wrapper.m_Shifter_Reverse;
        public InputAction @Gear1 => m_Wrapper.m_Shifter_Gear1;
        public InputAction @Gear2 => m_Wrapper.m_Shifter_Gear2;
        public InputAction @Gear3 => m_Wrapper.m_Shifter_Gear3;
        public InputAction @Gear4 => m_Wrapper.m_Shifter_Gear4;
        public InputAction @Gear5 => m_Wrapper.m_Shifter_Gear5;
        public InputAction @Gear6 => m_Wrapper.m_Shifter_Gear6;
        public InputAction @AutomaticDrive => m_Wrapper.m_Shifter_AutomaticDrive;
        public InputAction @AutomaticParking => m_Wrapper.m_Shifter_AutomaticParking;
        public InputAction @AutomaticReverse => m_Wrapper.m_Shifter_AutomaticReverse;
        public InputAction @AutomaticSport => m_Wrapper.m_Shifter_AutomaticSport;
        public InputAction @AutomaticManual => m_Wrapper.m_Shifter_AutomaticManual;
        public InputAction @GearUp => m_Wrapper.m_Shifter_GearUp;
        public InputAction @GearDown => m_Wrapper.m_Shifter_GearDown;
        public InputActionMap Get() { return m_Wrapper.m_Shifter; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShifterActions set) { return set.Get(); }
        public void AddCallbacks(IShifterActions instance)
        {
            if (instance == null || m_Wrapper.m_ShifterActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ShifterActionsCallbackInterfaces.Add(instance);
            @Reverse.started += instance.OnReverse;
            @Reverse.performed += instance.OnReverse;
            @Reverse.canceled += instance.OnReverse;
            @Gear1.started += instance.OnGear1;
            @Gear1.performed += instance.OnGear1;
            @Gear1.canceled += instance.OnGear1;
            @Gear2.started += instance.OnGear2;
            @Gear2.performed += instance.OnGear2;
            @Gear2.canceled += instance.OnGear2;
            @Gear3.started += instance.OnGear3;
            @Gear3.performed += instance.OnGear3;
            @Gear3.canceled += instance.OnGear3;
            @Gear4.started += instance.OnGear4;
            @Gear4.performed += instance.OnGear4;
            @Gear4.canceled += instance.OnGear4;
            @Gear5.started += instance.OnGear5;
            @Gear5.performed += instance.OnGear5;
            @Gear5.canceled += instance.OnGear5;
            @Gear6.started += instance.OnGear6;
            @Gear6.performed += instance.OnGear6;
            @Gear6.canceled += instance.OnGear6;
            @AutomaticDrive.started += instance.OnAutomaticDrive;
            @AutomaticDrive.performed += instance.OnAutomaticDrive;
            @AutomaticDrive.canceled += instance.OnAutomaticDrive;
            @AutomaticParking.started += instance.OnAutomaticParking;
            @AutomaticParking.performed += instance.OnAutomaticParking;
            @AutomaticParking.canceled += instance.OnAutomaticParking;
            @AutomaticReverse.started += instance.OnAutomaticReverse;
            @AutomaticReverse.performed += instance.OnAutomaticReverse;
            @AutomaticReverse.canceled += instance.OnAutomaticReverse;
            @AutomaticSport.started += instance.OnAutomaticSport;
            @AutomaticSport.performed += instance.OnAutomaticSport;
            @AutomaticSport.canceled += instance.OnAutomaticSport;
            @AutomaticManual.started += instance.OnAutomaticManual;
            @AutomaticManual.performed += instance.OnAutomaticManual;
            @AutomaticManual.canceled += instance.OnAutomaticManual;
            @GearUp.started += instance.OnGearUp;
            @GearUp.performed += instance.OnGearUp;
            @GearUp.canceled += instance.OnGearUp;
            @GearDown.started += instance.OnGearDown;
            @GearDown.performed += instance.OnGearDown;
            @GearDown.canceled += instance.OnGearDown;
        }

        private void UnregisterCallbacks(IShifterActions instance)
        {
            @Reverse.started -= instance.OnReverse;
            @Reverse.performed -= instance.OnReverse;
            @Reverse.canceled -= instance.OnReverse;
            @Gear1.started -= instance.OnGear1;
            @Gear1.performed -= instance.OnGear1;
            @Gear1.canceled -= instance.OnGear1;
            @Gear2.started -= instance.OnGear2;
            @Gear2.performed -= instance.OnGear2;
            @Gear2.canceled -= instance.OnGear2;
            @Gear3.started -= instance.OnGear3;
            @Gear3.performed -= instance.OnGear3;
            @Gear3.canceled -= instance.OnGear3;
            @Gear4.started -= instance.OnGear4;
            @Gear4.performed -= instance.OnGear4;
            @Gear4.canceled -= instance.OnGear4;
            @Gear5.started -= instance.OnGear5;
            @Gear5.performed -= instance.OnGear5;
            @Gear5.canceled -= instance.OnGear5;
            @Gear6.started -= instance.OnGear6;
            @Gear6.performed -= instance.OnGear6;
            @Gear6.canceled -= instance.OnGear6;
            @AutomaticDrive.started -= instance.OnAutomaticDrive;
            @AutomaticDrive.performed -= instance.OnAutomaticDrive;
            @AutomaticDrive.canceled -= instance.OnAutomaticDrive;
            @AutomaticParking.started -= instance.OnAutomaticParking;
            @AutomaticParking.performed -= instance.OnAutomaticParking;
            @AutomaticParking.canceled -= instance.OnAutomaticParking;
            @AutomaticReverse.started -= instance.OnAutomaticReverse;
            @AutomaticReverse.performed -= instance.OnAutomaticReverse;
            @AutomaticReverse.canceled -= instance.OnAutomaticReverse;
            @AutomaticSport.started -= instance.OnAutomaticSport;
            @AutomaticSport.performed -= instance.OnAutomaticSport;
            @AutomaticSport.canceled -= instance.OnAutomaticSport;
            @AutomaticManual.started -= instance.OnAutomaticManual;
            @AutomaticManual.performed -= instance.OnAutomaticManual;
            @AutomaticManual.canceled -= instance.OnAutomaticManual;
            @GearUp.started -= instance.OnGearUp;
            @GearUp.performed -= instance.OnGearUp;
            @GearUp.canceled -= instance.OnGearUp;
            @GearDown.started -= instance.OnGearDown;
            @GearDown.performed -= instance.OnGearDown;
            @GearDown.canceled -= instance.OnGearDown;
        }

        public void RemoveCallbacks(IShifterActions instance)
        {
            if (m_Wrapper.m_ShifterActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IShifterActions instance)
        {
            foreach (var item in m_Wrapper.m_ShifterActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ShifterActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ShifterActions @Shifter => new ShifterActions(this);

    // Functions
    private readonly InputActionMap m_Functions;
    private List<IFunctionsActions> m_FunctionsActionsCallbackInterfaces = new List<IFunctionsActions>();
    private readonly InputAction m_Functions_Ignition;
    private readonly InputAction m_Functions_Starter;
    private readonly InputAction m_Functions_ParkingBrake;
    private readonly InputAction m_Functions_LeftBlinker;
    private readonly InputAction m_Functions_RightBlinker;
    private readonly InputAction m_Functions_LeftComfortBlinker;
    private readonly InputAction m_Functions_RightComfortBlinker;
    private readonly InputAction m_Functions_Hazards;
    public struct FunctionsActions
    {
        private @VehicleInputActions m_Wrapper;
        public FunctionsActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Ignition => m_Wrapper.m_Functions_Ignition;
        public InputAction @Starter => m_Wrapper.m_Functions_Starter;
        public InputAction @ParkingBrake => m_Wrapper.m_Functions_ParkingBrake;
        public InputAction @LeftBlinker => m_Wrapper.m_Functions_LeftBlinker;
        public InputAction @RightBlinker => m_Wrapper.m_Functions_RightBlinker;
        public InputAction @LeftComfortBlinker => m_Wrapper.m_Functions_LeftComfortBlinker;
        public InputAction @RightComfortBlinker => m_Wrapper.m_Functions_RightComfortBlinker;
        public InputAction @Hazards => m_Wrapper.m_Functions_Hazards;
        public InputActionMap Get() { return m_Wrapper.m_Functions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FunctionsActions set) { return set.Get(); }
        public void AddCallbacks(IFunctionsActions instance)
        {
            if (instance == null || m_Wrapper.m_FunctionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FunctionsActionsCallbackInterfaces.Add(instance);
            @Ignition.started += instance.OnIgnition;
            @Ignition.performed += instance.OnIgnition;
            @Ignition.canceled += instance.OnIgnition;
            @Starter.started += instance.OnStarter;
            @Starter.performed += instance.OnStarter;
            @Starter.canceled += instance.OnStarter;
            @ParkingBrake.started += instance.OnParkingBrake;
            @ParkingBrake.performed += instance.OnParkingBrake;
            @ParkingBrake.canceled += instance.OnParkingBrake;
            @LeftBlinker.started += instance.OnLeftBlinker;
            @LeftBlinker.performed += instance.OnLeftBlinker;
            @LeftBlinker.canceled += instance.OnLeftBlinker;
            @RightBlinker.started += instance.OnRightBlinker;
            @RightBlinker.performed += instance.OnRightBlinker;
            @RightBlinker.canceled += instance.OnRightBlinker;
            @LeftComfortBlinker.started += instance.OnLeftComfortBlinker;
            @LeftComfortBlinker.performed += instance.OnLeftComfortBlinker;
            @LeftComfortBlinker.canceled += instance.OnLeftComfortBlinker;
            @RightComfortBlinker.started += instance.OnRightComfortBlinker;
            @RightComfortBlinker.performed += instance.OnRightComfortBlinker;
            @RightComfortBlinker.canceled += instance.OnRightComfortBlinker;
            @Hazards.started += instance.OnHazards;
            @Hazards.performed += instance.OnHazards;
            @Hazards.canceled += instance.OnHazards;
        }

        private void UnregisterCallbacks(IFunctionsActions instance)
        {
            @Ignition.started -= instance.OnIgnition;
            @Ignition.performed -= instance.OnIgnition;
            @Ignition.canceled -= instance.OnIgnition;
            @Starter.started -= instance.OnStarter;
            @Starter.performed -= instance.OnStarter;
            @Starter.canceled -= instance.OnStarter;
            @ParkingBrake.started -= instance.OnParkingBrake;
            @ParkingBrake.performed -= instance.OnParkingBrake;
            @ParkingBrake.canceled -= instance.OnParkingBrake;
            @LeftBlinker.started -= instance.OnLeftBlinker;
            @LeftBlinker.performed -= instance.OnLeftBlinker;
            @LeftBlinker.canceled -= instance.OnLeftBlinker;
            @RightBlinker.started -= instance.OnRightBlinker;
            @RightBlinker.performed -= instance.OnRightBlinker;
            @RightBlinker.canceled -= instance.OnRightBlinker;
            @LeftComfortBlinker.started -= instance.OnLeftComfortBlinker;
            @LeftComfortBlinker.performed -= instance.OnLeftComfortBlinker;
            @LeftComfortBlinker.canceled -= instance.OnLeftComfortBlinker;
            @RightComfortBlinker.started -= instance.OnRightComfortBlinker;
            @RightComfortBlinker.performed -= instance.OnRightComfortBlinker;
            @RightComfortBlinker.canceled -= instance.OnRightComfortBlinker;
            @Hazards.started -= instance.OnHazards;
            @Hazards.performed -= instance.OnHazards;
            @Hazards.canceled -= instance.OnHazards;
        }

        public void RemoveCallbacks(IFunctionsActions instance)
        {
            if (m_Wrapper.m_FunctionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFunctionsActions instance)
        {
            foreach (var item in m_Wrapper.m_FunctionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FunctionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FunctionsActions @Functions => new FunctionsActions(this);

    // View
    private readonly InputActionMap m_View;
    private List<IViewActions> m_ViewActionsCallbackInterfaces = new List<IViewActions>();
    private readonly InputAction m_View_ChangeVehicleView;
    private readonly InputAction m_View_DriverView;
    private readonly InputAction m_View_View1;
    private readonly InputAction m_View_DashboardView;
    private readonly InputAction m_View_InfotainmentView;
    public struct ViewActions
    {
        private @VehicleInputActions m_Wrapper;
        public ViewActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ChangeVehicleView => m_Wrapper.m_View_ChangeVehicleView;
        public InputAction @DriverView => m_Wrapper.m_View_DriverView;
        public InputAction @View1 => m_Wrapper.m_View_View1;
        public InputAction @DashboardView => m_Wrapper.m_View_DashboardView;
        public InputAction @InfotainmentView => m_Wrapper.m_View_InfotainmentView;
        public InputActionMap Get() { return m_Wrapper.m_View; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ViewActions set) { return set.Get(); }
        public void AddCallbacks(IViewActions instance)
        {
            if (instance == null || m_Wrapper.m_ViewActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ViewActionsCallbackInterfaces.Add(instance);
            @ChangeVehicleView.started += instance.OnChangeVehicleView;
            @ChangeVehicleView.performed += instance.OnChangeVehicleView;
            @ChangeVehicleView.canceled += instance.OnChangeVehicleView;
            @DriverView.started += instance.OnDriverView;
            @DriverView.performed += instance.OnDriverView;
            @DriverView.canceled += instance.OnDriverView;
            @View1.started += instance.OnView1;
            @View1.performed += instance.OnView1;
            @View1.canceled += instance.OnView1;
            @DashboardView.started += instance.OnDashboardView;
            @DashboardView.performed += instance.OnDashboardView;
            @DashboardView.canceled += instance.OnDashboardView;
            @InfotainmentView.started += instance.OnInfotainmentView;
            @InfotainmentView.performed += instance.OnInfotainmentView;
            @InfotainmentView.canceled += instance.OnInfotainmentView;
        }

        private void UnregisterCallbacks(IViewActions instance)
        {
            @ChangeVehicleView.started -= instance.OnChangeVehicleView;
            @ChangeVehicleView.performed -= instance.OnChangeVehicleView;
            @ChangeVehicleView.canceled -= instance.OnChangeVehicleView;
            @DriverView.started -= instance.OnDriverView;
            @DriverView.performed -= instance.OnDriverView;
            @DriverView.canceled -= instance.OnDriverView;
            @View1.started -= instance.OnView1;
            @View1.performed -= instance.OnView1;
            @View1.canceled -= instance.OnView1;
            @DashboardView.started -= instance.OnDashboardView;
            @DashboardView.performed -= instance.OnDashboardView;
            @DashboardView.canceled -= instance.OnDashboardView;
            @InfotainmentView.started -= instance.OnInfotainmentView;
            @InfotainmentView.performed -= instance.OnInfotainmentView;
            @InfotainmentView.canceled -= instance.OnInfotainmentView;
        }

        public void RemoveCallbacks(IViewActions instance)
        {
            if (m_Wrapper.m_ViewActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IViewActions instance)
        {
            foreach (var item in m_Wrapper.m_ViewActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ViewActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ViewActions @View => new ViewActions(this);

    // Trip Computer
    private readonly InputActionMap m_TripComputer;
    private List<ITripComputerActions> m_TripComputerActionsCallbackInterfaces = new List<ITripComputerActions>();
    private readonly InputAction m_TripComputer_Newaction;
    public struct TripComputerActions
    {
        private @VehicleInputActions m_Wrapper;
        public TripComputerActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_TripComputer_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_TripComputer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TripComputerActions set) { return set.Get(); }
        public void AddCallbacks(ITripComputerActions instance)
        {
            if (instance == null || m_Wrapper.m_TripComputerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TripComputerActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(ITripComputerActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(ITripComputerActions instance)
        {
            if (m_Wrapper.m_TripComputerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITripComputerActions instance)
        {
            foreach (var item in m_Wrapper.m_TripComputerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TripComputerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TripComputerActions @TripComputer => new TripComputerActions(this);
    private int m_KeyboardandMouseSchemeIndex = -1;
    public InputControlScheme KeyboardandMouseScheme
    {
        get
        {
            if (m_KeyboardandMouseSchemeIndex == -1) m_KeyboardandMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard and Mouse");
            return asset.controlSchemes[m_KeyboardandMouseSchemeIndex];
        }
    }
    public interface IDriveActions
    {
        void OnGasPedal(InputAction.CallbackContext context);
        void OnBrakePedal(InputAction.CallbackContext context);
        void OnClutchPedal(InputAction.CallbackContext context);
        void OnSteeringWheel(InputAction.CallbackContext context);
    }
    public interface IShifterActions
    {
        void OnReverse(InputAction.CallbackContext context);
        void OnGear1(InputAction.CallbackContext context);
        void OnGear2(InputAction.CallbackContext context);
        void OnGear3(InputAction.CallbackContext context);
        void OnGear4(InputAction.CallbackContext context);
        void OnGear5(InputAction.CallbackContext context);
        void OnGear6(InputAction.CallbackContext context);
        void OnAutomaticDrive(InputAction.CallbackContext context);
        void OnAutomaticParking(InputAction.CallbackContext context);
        void OnAutomaticReverse(InputAction.CallbackContext context);
        void OnAutomaticSport(InputAction.CallbackContext context);
        void OnAutomaticManual(InputAction.CallbackContext context);
        void OnGearUp(InputAction.CallbackContext context);
        void OnGearDown(InputAction.CallbackContext context);
    }
    public interface IFunctionsActions
    {
        void OnIgnition(InputAction.CallbackContext context);
        void OnStarter(InputAction.CallbackContext context);
        void OnParkingBrake(InputAction.CallbackContext context);
        void OnLeftBlinker(InputAction.CallbackContext context);
        void OnRightBlinker(InputAction.CallbackContext context);
        void OnLeftComfortBlinker(InputAction.CallbackContext context);
        void OnRightComfortBlinker(InputAction.CallbackContext context);
        void OnHazards(InputAction.CallbackContext context);
    }
    public interface IViewActions
    {
        void OnChangeVehicleView(InputAction.CallbackContext context);
        void OnDriverView(InputAction.CallbackContext context);
        void OnView1(InputAction.CallbackContext context);
        void OnDashboardView(InputAction.CallbackContext context);
        void OnInfotainmentView(InputAction.CallbackContext context);
    }
    public interface ITripComputerActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
